In [ ]:
from google.colab import drive
drive.mount('/content/drive')

KeyboardInterrupt: ignored

from tensorflow.keras.applications import ResNet50
from tensorflow.keras.applications.resnet50 import preprocess_input
from PIL import Image
import numpy as np

resnet_model = ResNet50(weights='imagenet', include_top=False)

img_path = '/content/drive/MyDrive/인공지능팀플/다리올/다리올01.jpg'

image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)  # BGR to RGB
img_pil = Image.open(img_path).resize((224, 224))
img = np.array(img_pil)

x = np.expand_dims(img, axis=0)
x = preprocess_input(x)

features1 = resnet_model.predict(x)

print(features1.shape)
print(features1)

In [ ]:
import os
import numpy as np
import cv2
from tensorflow.keras.applications.resnet50 import ResNet50, preprocess_input

# 코랩 폴더 경로
folder_path = '/content/drive/MyDrive/DatabasedAI/다리올'

# ResNet50 모델 로드
resnet_model = ResNet50(weights='imagenet', include_top=False)


# 이미지 파일명 가져오기
image_files = sorted([file for file in os.listdir(folder_path) if file.lower().endswith(('.jpg', '.jpeg', '.png'))])


# 이미지 특징 벡터를 저장할 배열 초기화
features = np.zeros((len(image_files), 7, 7, 2048))

# 특징 벡터 추출
for i, image_file in enumerate(image_files):
    img_path = os.path.join(folder_path, image_file)
    image = cv2.imread(img_path)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    image = cv2.resize(image, (224, 224))
    image = np.expand_dims(image, axis=0)
    image = preprocess_input(image)
    features[i] = resnet_model.predict(image)

# features.npy 파일 경로
save_path = 'features.npy'

# features.npy 파일로 저장
np.save(save_path, features)

# 특징 벡터 불러오기
features = np.load(save_path)
print(features[0])


1/1 [==============================] - 0s 358ms/step
[[[ 0.          0.          0.         ...  1.38221288  0.
    0.        ]
  [ 0.          0.          0.         ...  0.          0.
    0.        ]
  [ 0.          0.          0.         ...  0.          0.
    0.        ]
  ...
  [ 0.          0.          0.         ...  3.13946772  0.
    0.        ]
  [ 0.          0.          0.         ...  1.45088303  0.
    0.        ]
  [ 0.          0.          0.         ...  0.          0.
    0.        ]]

 [[ 0.          0.          0.         ...  0.38049412  0.
    0.        ]
  [ 0.          0.          0.         ...  3.0982635   0.
    0.        ]
  [ 0.          0.          0.         ...  3.93651295  0.
    0.        ]
  ...
  [ 0.          0.69023097  0.         ...  0.36487758  0.
    0.        ]
  [ 2.36655903  0.          0.         ...  6.40408182  0.
    0.        ]
  [ 0.          0.          0.         ...  2.14646387  0.
    0.        ]]

 [[ 0.          0.          0. 

In [ ]:
import numpy as np

# features.npy 파일 경로
save_path = 'features.npy'

# features.npy 파일로 저장
np.save(save_path, features)


# 특징 벡터 불러오기
features = np.load('features.npy')

# 특징 벡터 사용 예시
print(features.shape)  # 특징 벡터 배열의 크기 출력

(90, 7, 7, 2048)


In [ ]:
print(features[0])

[[[ 0.          0.          0.         ...  1.38221288  0.
    0.        ]
  [ 0.          0.          0.         ...  0.          0.
    0.        ]
  [ 0.          0.          0.         ...  0.          0.
    0.        ]
  ...
  [ 0.          0.          0.         ...  3.13946772  0.
    0.        ]
  [ 0.          0.          0.         ...  1.45088303  0.
    0.        ]
  [ 0.          0.          0.         ...  0.          0.
    0.        ]]

 [[ 0.          0.          0.         ...  0.38049412  0.
    0.        ]
  [ 0.          0.          0.         ...  3.0982635   0.
    0.        ]
  [ 0.          0.          0.         ...  3.93651295  0.
    0.        ]
  ...
  [ 0.          0.69023097  0.         ...  0.36487758  0.
    0.        ]
  [ 2.36655903  0.          0.         ...  6.40408182  0.
    0.        ]
  [ 0.          0.          0.         ...  2.14646387  0.
    0.        ]]

 [[ 0.          0.          0.         ...  0.44695306  0.
    0.        ]
  [ 0.   

In [ ]:
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.applications.resnet50 import preprocess_input
from PIL import Image
import numpy as np
import cv2

resnet_model = ResNet50(weights='imagenet', include_top=False)

folder_path = '/content/drive/MyDrive/DatabasedAI/다리올'
img_path = '/content/drive/MyDrive/DatabasedAI/다리올/다리올01.jpg'

# 이미지 불러오기
image = cv2.imread(img_path)
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
image = cv2.resize(image, (224, 224))

# 이미지 전처리 및 특징 벡터 추출
x = np.expand_dims(image, axis=0)
x = preprocess_input(x)
features1 = resnet_model.predict(x)

print(features1.shape)
print(features1)


1/1 [==============================] - 2s 2s/step
(1, 7, 7, 2048)
[[[[ 0.          0.          0.         ...  1.3822129   0.
     0.        ]
   [ 0.          0.          0.         ...  0.          0.
     0.        ]
   [ 0.          0.          0.         ...  0.          0.
     0.        ]
   ...
   [ 0.          0.          0.         ...  3.1394677   0.
     0.        ]
   [ 0.          0.          0.         ...  1.450883    0.
     0.        ]
   [ 0.          0.          0.         ...  0.          0.
     0.        ]]

  [[ 0.          0.          0.         ...  0.38049412  0.
     0.        ]
   [ 0.          0.          0.         ...  3.0982635   0.
     0.        ]
   [ 0.          0.          0.         ...  3.936513    0.
     0.        ]
   ...
   [ 0.          0.69023097  0.         ...  0.36487758  0.
     0.        ]
   [ 2.366559    0.          0.         ...  6.404082    0.
     0.        ]
   [ 0.          0.          0.         ...  2.1464639   0.
     0.    

In [ ]:
features[0]==features1

array([[[[ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         ...,
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True]],

        [[ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         ...,
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True]],

        [[ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         ...,
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  T

## 인셉션

In [ ]:
import os
import numpy as np
import cv2
from tensorflow.keras.applications.inception_v3 import InceptionV3, preprocess_input

# 코랩 폴더 경로
folder_path = '/content/drive/MyDrive/DatabasedAI/다리올'

# InceptionV3 모델 로드
inception_model = InceptionV3(weights='imagenet', include_top=False)

# 이미지 파일명 가져오기
image_files = sorted([file for file in os.listdir(folder_path) if file.lower().endswith(('.jpg', '.jpeg', '.png'))])

# 이미지 특징 벡터를 저장할 배열 초기화
features = np.zeros((len(image_files), 5, 5, 2048))

# 특징 벡터 추출
for i, image_file in enumerate(image_files):
    img_path = os.path.join(folder_path, image_file)
    image = cv2.imread(img_path)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    image = cv2.resize(image, (224, 224))
    image = np.expand_dims(image, axis=0)
    image = preprocess_input(image)
    features[i] = inception_model.predict(image)

# features.npy 파일 경로
save_path = 'features.npy'

# features.npy 파일로 저장
np.save(save_path, features)

# 특징 벡터 불러오기
features = np.load(save_path)
print(features[0])


1/1 [==============================] - 0s 146ms/step
[[[0.         0.64089394 0.         ... 0.         1.3923192  0.10443056]
  [0.         0.         0.         ... 0.         1.18174732 0.        ]
  [3.71186113 0.         0.         ... 0.         0.70883256 0.        ]
  [3.23319006 0.         0.11325338 ... 0.23215356 0.51228046 0.        ]
  [0.63862932 0.         0.48946473 ... 0.59815848 0.38811898 0.        ]]

 [[0.         0.         0.         ... 0.         0.80931467 0.20741144]
  [0.         0.         0.         ... 0.         0.75794244 0.06173496]
  [4.77586412 0.         4.7766571  ... 0.         0.73760223 0.        ]
  [5.23425055 0.         4.24048185 ... 0.         0.70775723 0.        ]
  [0.82571065 0.         1.53722084 ... 0.23409255 0.73403728 0.        ]]

 [[0.         0.         0.         ... 0.         0.31640849 0.54019332]
  [0.         0.         0.         ... 0.         0.43604794 0.45010313]
  [3.10801268 0.         2.0789969  ... 0.         0.86

In [ ]:
import numpy as np

# features.npy 파일 경로
save_path = 'features.npy'

# features.npy 파일로 저장
np.save(save_path, features)


# 특징 벡터 불러오기
features = np.load('features.npy')

# 특징 벡터 사용 예시
print(features.shape)  # 특징 벡터 배열의 크기 출력
print(features[0])

(90, 5, 5, 2048)
[[[0.         0.64089394 0.         ... 0.         1.3923192  0.10443056]
  [0.         0.         0.         ... 0.         1.18174732 0.        ]
  [3.71186113 0.         0.         ... 0.         0.70883256 0.        ]
  [3.23319006 0.         0.11325338 ... 0.23215356 0.51228046 0.        ]
  [0.63862932 0.         0.48946473 ... 0.59815848 0.38811898 0.        ]]

 [[0.         0.         0.         ... 0.         0.80931467 0.20741144]
  [0.         0.         0.         ... 0.         0.75794244 0.06173496]
  [4.77586412 0.         4.7766571  ... 0.         0.73760223 0.        ]
  [5.23425055 0.         4.24048185 ... 0.         0.70775723 0.        ]
  [0.82571065 0.         1.53722084 ... 0.23409255 0.73403728 0.        ]]

 [[0.         0.         0.         ... 0.         0.31640849 0.54019332]
  [0.         0.         0.         ... 0.         0.43604794 0.45010313]
  [3.10801268 0.         2.0789969  ... 0.         0.86042303 0.        ]
  [3.82360148 0. 

In [ ]:
from tensorflow.keras.applications import InceptionV3
from tensorflow.keras.applications.inception_v3 import preprocess_input
from PIL import Image
import numpy as np
import cv2

inception_model = InceptionV3(weights='imagenet', include_top=False)

folder_path = '/content/drive/MyDrive/DatabasedAI/다리올'
img_path = '/content/drive/MyDrive/DatabasedAI/다리올/다리올01.jpg'

# 이미지 불러오기
image = cv2.imread(img_path)
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
image = cv2.resize(image, (224, 224))

# 이미지 전처리 및 특징 벡터 추출
x = np.expand_dims(image, axis=0)
x = preprocess_input(x)
features1 = inception_model.predict(x)

print(features1.shape)
print(features1)


1/1 [==============================] - 2s 2s/step
(1, 5, 5, 2048)
[[[[0.         0.64089394 0.         ... 0.         1.3923192
    0.10443056]
   [0.         0.         0.         ... 0.         1.1817473
    0.        ]
   [3.7118611  0.         0.         ... 0.         0.70883256
    0.        ]
   [3.23319    0.         0.11325338 ... 0.23215356 0.51228046
    0.        ]
   [0.6386293  0.         0.48946473 ... 0.5981585  0.38811898
    0.        ]]

  [[0.         0.         0.         ... 0.         0.80931467
    0.20741144]
   [0.         0.         0.         ... 0.         0.75794244
    0.06173496]
   [4.775864   0.         4.776657   ... 0.         0.73760223
    0.        ]
   [5.2342505  0.         4.240482   ... 0.         0.70775723
    0.        ]
   [0.82571065 0.         1.5372208  ... 0.23409255 0.7340373
    0.        ]]

  [[0.         0.         0.         ... 0.         0.3164085
    0.5401933 ]
   [0.         0.         0.         ... 0.         0.43604794
  

In [ ]:
features[0]==features1

array([[[[ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True]],

        [[ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True]],

        [[ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True]],

        [[ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
        